apiVersion: v1
data:
  enableLfs: dHJ1ZQ==
  insecure: dHJ1ZQ==
  name: YXJnby10ZXN0LXJlcG8K
  sshPrivateKey: LS0t...
  project: ZGVmYXVsdA==
  url: Z2l0QGdpdGh1Yi5jb206c3ViaGFkZWVwLTEyMy9hcmdvLXRlc3QuZ2l0
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: github-ssh
  namespace: argocd
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  slack-token: "xoxb-insert-rest-of-the-token"